### ISSUE TITLE
Voice PR Tracker

### ISSUE THREAD

**Issue by lkloon123** [MoceanAPI/MIP#5]
- [x] php https://github.com/MoceanAPI/mocean-sdk-php/pull/10
- [x] nodejs https://github.com/MoceanAPI/mocean-sdk-nodejs/pull/4
- [x] java https://github.com/MoceanAPI/mocean-sdk-java/pull/14
- [x] dotnet https://github.com/MoceanAPI/mocean-sdk-dotnet/pull/9
- [x] python https://github.com/MoceanAPI/mocean-sdk-python/pull/4
- [x] ruby https://github.com/MoceanAPI/mocean-sdk-ruby/pull/3
- [x] dart https://github.com/MoceanAPI/mocean-sdk-dart/pull/2
- [x] go https://github.com/MoceanAPI/mocean-sdk-go/pull/1
